// Comprehensive story tags for categorization

export const storyTags = {
  mood: [
    "Dark and Gripping",
    "Light and Warm",
    "Emotional Wreck",
    "Feel Good",
    "Bittersweet",
    "Intense",
    "Slow Burn",
    "Fast Paced",
    "Heartbreaking",
    "Hopeful",
    "Funny and Real",
    "Quietly Devastating",
    "Edge of Your Seat",
    "Soft and Aching",
    "Angry and Alive",
  ],
  themes: [
    "Identity",
    "Family Secrets",
    "First Love",
    "Friendship Betrayal",
    "Coming of Age",
    "Survival",
    "Ambition",
    "Loyalty",
    "Forgiveness",
    "Grief",
    "Belonging",
    "Class and Money",
    "Cultural Clash",
    "Mother and Daughter",
    "Father and Son",
    "Sisterhood",
    "Brotherhood",
    "Finding Your Voice",
    "Chosen Family",
    "Standing Up",
    "Letting Go",
    "Growing Up Too Fast",
    "The Cost of Success",
    "Carrying Someone Else's Dream",
  ],
  relationships: [
    "Enemies to Friends",
    "Enemies to Lovers",
    "Forbidden Love",
    "Slow Burn Romance",
    "Best Friends",
    "Toxic Friendship",
    "Found Family",
    "Star Crossed Lovers",
    "Complicated Family",
    "Unlikely Alliance",
    "Mentor and Student",
    "Rivals",
    "Secret Relationship",
    "Long Distance",
    "One Sided Love",
    "Love Triangle",
    "Childhood Friends",
    "Strangers to Lovers",
  ],
  plot: [
    "Secret Revealed",
    "Race Against Time",
    "Hidden Identity",
    "Missing Person",
    "Chosen One",
    "Underdog",
    "Redemption Arc",
    "Revenge",
    "Escape",
    "Sacrifice",
    "Conspiracy",
    "Double Life",
    "Mystery to Solve",
    "Countdown",
    "The Truth Comes Out",
    "Running From the Past",
    "Second Chances",
    "Everything Changes",
    "Unexpected Hero",
    "The Wrong Person Gets Blamed",
  ],
  settings: [
    "Boarding School",
    "Big City",
    "Village Life",
    "Market Life",
    "Street Life",
    "Palace and Power",
    "Two Worlds Colliding",
    "Lagos",
    "Nairobi",
    "Accra",
    "Kigali",
    "Cape Town",
    "Addis Ababa",
    "Harare",
    "Enugu",
    "Kumasi",
    "Dakar",
    "Cairo",
    "Port Harcourt",
    "The Niger Delta",
    "The Highlands",
    "The Desert",
    "Waterside",
  ],
  genres: [
    "Romance",
    "Thriller",
    "Mystery",
    "Fantasy",
    "Mythology",
    "School Life",
    "Family Drama",
    "Street Hustle",
    "Supernatural",
    "Historical Fiction",
    "Contemporary",
    "Magical Realism",
    "Adventure",
    "Psychological",
    "Spiritual",
  ],
  africanCulture: [
    "Yoruba Mythology",
    "Igbo Tradition",
    "Akan Culture",
    "Wolof Tradition",
    "Xhosa Heritage",
    "Shona History",
    "Rwandan History",
    "Ethiopian Heritage",
    "Sufi Culture",
    "Great Zimbabwe",
    "Griot Tradition",
    "Masquerade",
    "Water Spirits",
    "Ancestral Gifts",
    "Old Magic",
    "Sacred Ruins",
    "The Old Ways",
    "Oral Tradition",
    "Lobola",
    "Festival Season",
  ],
  characters: [
    "Strong Girl",
    "Quiet Boy Who Sees Everything",
    "Girl Who Refuses",
    "Boy Learning to Speak",
    "Girl Running From Something",
    "Boy Running Toward Something",
    "The Scholarship Kid",
    "The Rich Kid With Problems",
    "The Invisible One",
    "The One Everyone Underestimates",
    "The Firstborn",
    "The Forgotten Middle Child",
    "The Youngest Who Notices Everything",
    "The One Who Left",
    "The One Who Stayed",
    "The Outsider",
    "The One Carrying the Family",
    "Girl With a Gift She Did Not Ask For",
    "Boy With a Secret That Is Not His Fault",
  ],
  emotionalExperience: [
    "This Will Make You Cry",
    "Read This Alone",
    "Share This With Your Best Friend",
    "Read This When You Are Angry",
    "Read This When You Feel Invisible",
    "Read This When You Miss Home",
    "Read This When You Feel Misunderstood",
    "Read This When You Are Falling in Love",
    "Read This When You Are Angry at Your Parents",
    "Read This When You Feel Like You Are Not Enough",
    "Read This When You Need to Feel Brave",
    "Read This When the World Feels Too Big",
    "This Will Change How You See Your Family",
    "This Will Change How You See Yourself",
    "You Will Not Sleep After This",
  ],
  lengthAndFormat: [
    "Quick Read",
    "Binge Worthy",
    "Cliffhanger Every Episode",
    "New Episode Weekly",
    "Completed Season",
    "Ongoing",
    "Three Seasons",
    "Fast Episodes",
    "Character Heavy",
    "Plot Heavy",
    "Dialogue Driven",
  ],
  content: [
    "Clean Romance",
    "Mild Violence",
    "Emotional Intensity",
    "Deals With Grief",
    "Deals With Abuse",
    "Deals With Family Trauma",
    "Deals With Identity",
    "Deals With Mental Health",
    "Deals With Class and Poverty",
    "Deals With Historical Trauma",
    "Parent Approved",
    "Teen Recommended",
    "Discussion Worthy",
  ],
  tropes: [
    "Wrong Side of the Tracks",
    "Secret Royalty",
    "Hidden Power",
    "The One Who Was Overlooked",
    "From Nothing to Everything",
    "Two Worlds One Heart",
    "The Prophecy",
    "The Sacrifice",
    "The Impossible Choice",
    "The Reveal That Changes Everything",
    "The Moment of No Return",
    "The Last Episode That Destroys You",
    "The Season Finale You Did Not See Coming",
  ],
  platform: [
    "Inkseries Original",
    "Staff Pick",
    "Reader Favorite",
    "Most Commented",
    "Trending in Nigeria",
    "Trending in Ghana",
    "Trending in Kenya",
    "Trending in South Africa",
    "New Season Dropping",
    "Fan Favorite Character",
    "Most Shocking Episode",
    "Episode Everyone is Talking About",
    "Season Finale Week",
    "Free Episodes Available",
  ],
} as const;

// Category labels for display
export const tagCategoryLabels: Record<keyof typeof storyTags, string> = {
  mood: "Mood",
  themes: "Themes",
  relationships: "Relationships",
  plot: "Plot",
  settings: "Settings",
  genres: "Genre",
  africanCulture: "African Mythology & Culture",
  characters: "Characters",
  emotionalExperience: "Emotional Experience",
  lengthAndFormat: "Length & Format",
  content: "Content",
  tropes: "Tropes",
  platform: "Platform",
};

// All tags flattened for easy lookup
export const allTags = [
  ...storyTags.mood,
  ...storyTags.themes,
  ...storyTags.relationships,
  ...storyTags.plot,
  ...storyTags.settings,
  ...storyTags.genres,
  ...storyTags.africanCulture,
  ...storyTags.characters,
  ...storyTags.emotionalExperience,
  ...storyTags.lengthAndFormat,
  ...storyTags.content,
  ...storyTags.tropes,
  ...storyTags.platform,
] as const;

export type StoryTag = (typeof allTags)[number];
export type TagCategory = keyof typeof storyTags;

// Popular tags to show first in filters
export const popularTags = [
  "Enemies to Lovers",
  "Slow Burn Romance",
  "Boarding School",
  "Strong Girl",
  "Coming of Age",
  "Dark and Gripping",
  "Lagos",
  "Yoruba Mythology",
  "Family Drama",
  "This Will Make You Cry",
  "Inkseries Original",
  "Staff Pick",
] as const;
